### ISSUE TITLE
Release TODO list.

### ISSUE THREAD

**Issue by frostu8** [frostu8/citrus#1]
Citrus is but a mere prototype right now. This is a list of tasks before I consider Citrus ready for use with modding 100% Orange Juice.

**Main**
- [x] Create a seemingly infinite space where a board can be comfortably built without having to worry about size constraints.
- [x] Add tile selection. The current method of right clicking to cycle through tiles does not count.
- [x] Add tile sprites to replace the color squares.
- [] Pan and zooming features.
    - [ ] Scale about cursor position.
    - [x] Pan about cursor.
- [ ] Directional editor. Ability to add "static" and "dynamic" exits to tiles.
    * Static exits do not change when under the influence of "Backtrack."
    * Dynamic exits do change when under the influence of "Backtrack."
- [ ] Exporting fields.

**Extra**
- [ ] Ability to switch between orthographic and isometric projections.
- [ ] Creating an extended format for saving dynamically sized fields to disk.
- [ ] Rendering a background instead of infinite white space.

**Flavor**
- [ ] Add links to the Github page and OJ Edit.
